//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPremiereApp.Ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderId { get; set; }
        public System.DateTime BuyDate { get; set; }
        public int FilmId { get; set; }
        public System.DateTime SessionDate { get; set; }
        public decimal Price { get; set; }
        public int CountTickets { get; set; }
        public Nullable<decimal> TotalSum { get; set; }
        public int PaymentTypeId { get; set; }
        public string Note { get; set; }
        public int UserId { get; set; }
    
        public virtual Films Films { get; set; }
        public virtual PaymentTypes PaymentTypes { get; set; }
        public virtual Users Users { get; set; }
    }
}
