; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Кинотеатр «Премьера»"
#define MyAppVersion "1.0"
#define MyAppPublisher "Мухин Вадим Юрьевич"
#define MyAppExeName "CinemaPremiereApp.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{D3946066-1FE7-46DA-B7AF-95F77D150E6D}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=C:\Users\Vadim\Desktop
OutputBaseFilename=CinemaPremiereApp_Setup
SetupIconFile=C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\Images\Logo.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\CinemaPremiereApp.exe.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\CinemaPremiereApp.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\CinemaPremiereDb_Script.sql"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\ClosedXML.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\ClosedXML.Parser.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\ClosedXML.Parser.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\ClosedXML.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\ClosedXML.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\DocumentFormat.OpenXml.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\DocumentFormat.OpenXml.Framework.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\DocumentFormat.OpenXml.Framework.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\DocumentFormat.OpenXml.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\EntityFramework.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\EntityFramework.SqlServer.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\EntityFramework.SqlServer.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\EntityFramework.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\ExcelNumberFormat.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\ExcelNumberFormat.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\MaterialDesignColors.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\MaterialDesignThemes.Wpf.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\MaterialDesignThemes.Wpf.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\Microsoft.Bcl.HashCode.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\Microsoft.Bcl.HashCode.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\Microsoft.Xaml.Behaviors.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\Microsoft.Xaml.Behaviors.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\Microsoft.Xaml.Behaviors.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\Newtonsoft.Json.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\Newtonsoft.Json.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\RBush.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\RBush.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\SetupDatabase.bat"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\SixLabors.Fonts.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\SixLabors.Fonts.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\System.Buffers.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\System.Buffers.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\System.Memory.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\System.Memory.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\System.Numerics.Vectors.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\System.Numerics.Vectors.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\System.Runtime.CompilerServices.Unsafe.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\System.Runtime.CompilerServices.Unsafe.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\Images\*"; DestDir: "{app}\Images"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\Vadim\Desktop\CinemaPremiere\App\CinemaPremiereApp\CinemaPremiereApp\bin\Release\ru\*"; DestDir: "{app}\ru"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Dirs]
Name: "{app}"; Permissions: users-modify

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\SetupDatabase.bat"; StatusMsg: "Настройка базы данных (это может занять несколько секунд)..."; Flags: runhidden waituntilterminated
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

